### PR TITLE
Create install-PAPI-5.4.1.sh

### PR DESCRIPTION
**Pull request by prashantrar**
script to install PAPI(performance API)

### CODE REVIEW

**Comment by kaosf** [comment]
I'm not sure what PAPI is. I only have read http://icl.cs.utk.edu/papi/ a bit just now.

I will merge this PR and add a description like "`install-PAPI-5.4.1.sh` script is created by @prashantar" to README.md. And more I will create a file e.g. `contributers.md` and write your name @prashantar there.

Is it OK?

**Comment by prashantrar** [comment]
Sounds good.

I was contributing these scripts as they are also useful tools in ubuntu installation and many people might need it.

PAPI is a performance api for linux based systems on arm as well as x86/x64 for benchmarking applications, a lot of software developers use them time to time.

**Comment by kaosf** [comment]
Thanks :smile:! I'll accept your this PR now.

And also about #1, I'll merge it.

**Comment by kaosf** [comment]
@prashantrar Do you have your Bitbucket account?

This repository is hosted also on [Bitbucket](https://bitbucket.org/kaosf/ubuntu-setup), so I write your Bitbucket account in `contributers.md` if you have it.

**Comment by prashantrar** [comment]
yes my bitbucket id is also prashantrar, in a few days I shall also put few more PR's there are many common softwares that many ubuntu programmers donot find and find it tricky to install from source.

**Comment by kaosf** [comment]
I added your name (on GitHub and Bitbucket) to README.md and contributers.md. Thank you.

I'm waiting your next PRs.

**Comment by prashantrar** [comment]
sure will do...

**Comment by kaosf** [comment]
take it easy :smiley:

**Pull request merged**
